name: Run tests

on: [push]

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'skipci')"
    runs-on: ubuntu-latest

    name: Run tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3.0.11
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-interaction

      - name: Execute tests
        run: ./vendor/bin/phpunit
